<script>
    import DynamicAttributes from "./DynamicAttributes.svelte";
    import StylingExample from "./StylingExample.svelte";
    import HTMLTags from "./HTMLTags.svelte";
    import Assignments from "../2_Reactivity/Assignments.svelte";
    import Declarations from "../2_Reactivity/Declarations.svelte";
    import Statements from "../2_Reactivity/Statements.svelte";
    import UpdatingArraysAndObjects from "../2_Reactivity/UpdatingArraysAndObjects.svelte";
    import DeclaringProps from "../3_Props/DeclaringProps.svelte";
    import SpreadProps from "../3_Props/SpreadProps.svelte";
    import IfBlocks from "../4_Logic/IfBlocks.svelte";
    import ElseBlocks from "../4_Logic/ElseBlocks.svelte";
    import ElseIfBlocks from "../4_Logic/ElseIfBlocks.svelte";
    import EachBlocks from "../4_Logic/EachBlocks.svelte";
    import KeyedEachBlocks from "../4_Logic/KeyedEachBlocks.svelte";
    import AwaitBlocks from "../4_Logic/AwaitBlocks.svelte";
    import DOMEvents from "../5_Events/DOMEvents.svelte";
    import EventModifiers from "../5_Events/EventModifiers.svelte";
    import ComponentEvents from "../5_Events/ComponentEvents.svelte";
    import EventForwarding from "../5_Events/EventForwarding.svelte";
    import DomEventForwarding from "../5_Events/DomEventForwarding.svelte";
    import TextInputs from "../6_Bindings/TextInputs.svelte";
    import NumericInputs from "../6_Bindings/NumericInputs.svelte";
    import CheckboxInputs from "../6_Bindings/CheckboxInputs.svelte";
    import GroupInputs from "../6_Bindings/GroupInputs.svelte";
    import TextareaInputs from "../6_Bindings/TextareaInputs.svelte";
    import SelectBindings from "../6_Bindings/SelectBindings.svelte";
    import SelectMultiple from "../6_Bindings/SelectMultiple.svelte";
    import ContentEditableBindings from "../6_Bindings/ContentEditableBindings.svelte";
    import EachBlockBindings from "../6_Bindings/EachBlockBindings.svelte";
    import MediaElements from "../6_Bindings/MediaElements.svelte";
    import Dimensions from "../6_Bindings/Dimensions.svelte";
    import This from "../6_Bindings/This.svelte";
    import ComponentBindings from "../6_Bindings/ComponentBindings.svelte";
    import OnMount from "../7_Lifecycle/OnMount.svelte";
    import OnDestroy from "../7_Lifecycle/OnDestroy.svelte";
    import BeforeAfterUpdate from "../7_Lifecycle/BeforeAfterUpdate.svelte";
    import Tick from "../7_Lifecycle/Tick.svelte";
    import WritableStore from "../8_Stores/WritableStore.svelte";
    import AutoSubscriptions from "../8_Stores/AutoSubscriptions.svelte";
    import ReadableStore from "../8_Stores/ReadableStore.svelte";
    import DerivedStore from "../8_Stores/DerivedStore.svelte";
    import ComponentStore from "../8_Stores/ComponentStore.svelte";
    import StoreBinding from "../8_Stores/StoreBinding.svelte";
    import Tweened from "../9_Motion/Tweened.svelte";
    import Spring from "../9_Motion/Spring.svelte";
    import TheTransitionDirective from "../10_Transitions/TheTransitionDirective.svelte";
    import AddingParameters from "../10_Transitions/AddingParameters.svelte";
    import InAndOut from "../10_Transitions/InAndOut.svelte";
    import CustomCSSTransition from "../10_Transitions/CustomCSSTransition.svelte";
    import CustomJSTransition from "../10_Transitions/CustomJSTransition.svelte";
    import TransitionEvents from "../10_Transitions/TransitionEvents.svelte";
    import LocalTransition from "../10_Transitions/LocalTransition.svelte";
    import DeferredTransition from "../10_Transitions/DeferredTransition.svelte";

    let name = 'world';
</script>
<h1>Introduction</h1>
<p>Hello {name}</p>